version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aais_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aais_database
      POSTGRES_USER: aais_user
      POSTGRES_PASSWORD: aais_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: aais_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
